### ISSUE TITLE
How do you ensure issuETH doens't run off with the bounties?

### ISSUE THREAD

**Issue by karalabe** [issuETH/issuETH#12]
If I understand correctly, issuETH is the one generating the public and private keypairs. Since the private key is generated by you, what guarantees does projects have that you won't run off with a large bounty?

Don't get me wrong, of course such a thing would mean the end of issuETH, but I'm talking about a potential hack that could collect all bounty funds from all projects.

**Comment by ligi** [comment]
Yes you understand correctly. But every project can run the bot on their own - the source is here - and only then you have a guarantee. Yes ideally we would use smart-contracts here - but IMHO currently the UX,Complexity and adoption would suffer for no good reason. But I am really open for suggestions here.
Currently my protection against a hack: as I currently mainly issue WALL tokens - I would just fork the token and invalidate the one from the attacker - DAO style ..-)

**Comment by ligi** [comment]
I opened #13 for discussing this further
